// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: upload.proto

package upload

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UploadStateService_GetUploadProcessingContext_FullMethodName = "/upload.UploadStateService/GetUploadProcessingContext"
	UploadStateService_UpdateUploadStatus_FullMethodName         = "/upload.UploadStateService/UpdateUploadStatus"
	UploadStateService_UpdateUploadStep_FullMethodName           = "/upload.UploadStateService/UpdateUploadStep"
	UploadStateService_UpdateVideoMetadata_FullMethodName        = "/upload.UploadStateService/UpdateVideoMetadata"
	UploadStateService_CreateUploadSteps_FullMethodName          = "/upload.UploadStateService/CreateUploadSteps"
	UploadStateService_CreateRenditions_FullMethodName           = "/upload.UploadStateService/CreateRenditions"
	UploadStateService_ListPendingRenditions_FullMethodName      = "/upload.UploadStateService/ListPendingRenditions"
	UploadStateService_UpdateRendition_FullMethodName            = "/upload.UploadStateService/UpdateRendition"
)

// UploadStateServiceClient is the client API for UploadStateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UploadStateServiceClient interface {
	GetUploadProcessingContext(ctx context.Context, in *GetUploadProcessingContextRequest, opts ...grpc.CallOption) (*GetUploadProcessingContextResponse, error)
	UpdateUploadStatus(ctx context.Context, in *UpdateUploadStatusRequest, opts ...grpc.CallOption) (*UpdateUploadStatusResponse, error)
	UpdateUploadStep(ctx context.Context, in *UpdateUploadStepRequest, opts ...grpc.CallOption) (*UpdateUploadStepResponse, error)
	UpdateVideoMetadata(ctx context.Context, in *UpdateVideoMetadataRequest, opts ...grpc.CallOption) (*UpdateVideoMetadataResponse, error)
	CreateUploadSteps(ctx context.Context, in *CreateUploadStepsRequest, opts ...grpc.CallOption) (*CreateUploadStepsResponse, error)
	CreateRenditions(ctx context.Context, in *CreateRenditionsRequest, opts ...grpc.CallOption) (*CreateRenditionsResponse, error)
	ListPendingRenditions(ctx context.Context, in *ListPendingRenditionsRequest, opts ...grpc.CallOption) (*ListPendingRenditionsResponse, error)
	UpdateRendition(ctx context.Context, in *UpdateRenditionRequest, opts ...grpc.CallOption) (*UpdateRenditionResponse, error)
}

type uploadStateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUploadStateServiceClient(cc grpc.ClientConnInterface) UploadStateServiceClient {
	return &uploadStateServiceClient{cc}
}

func (c *uploadStateServiceClient) GetUploadProcessingContext(ctx context.Context, in *GetUploadProcessingContextRequest, opts ...grpc.CallOption) (*GetUploadProcessingContextResponse, error) {
	out := new(GetUploadProcessingContextResponse)
	err := c.cc.Invoke(ctx, UploadStateService_GetUploadProcessingContext_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uploadStateServiceClient) UpdateUploadStatus(ctx context.Context, in *UpdateUploadStatusRequest, opts ...grpc.CallOption) (*UpdateUploadStatusResponse, error) {
	out := new(UpdateUploadStatusResponse)
	err := c.cc.Invoke(ctx, UploadStateService_UpdateUploadStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uploadStateServiceClient) UpdateUploadStep(ctx context.Context, in *UpdateUploadStepRequest, opts ...grpc.CallOption) (*UpdateUploadStepResponse, error) {
	out := new(UpdateUploadStepResponse)
	err := c.cc.Invoke(ctx, UploadStateService_UpdateUploadStep_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uploadStateServiceClient) UpdateVideoMetadata(ctx context.Context, in *UpdateVideoMetadataRequest, opts ...grpc.CallOption) (*UpdateVideoMetadataResponse, error) {
	out := new(UpdateVideoMetadataResponse)
	err := c.cc.Invoke(ctx, UploadStateService_UpdateVideoMetadata_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uploadStateServiceClient) CreateUploadSteps(ctx context.Context, in *CreateUploadStepsRequest, opts ...grpc.CallOption) (*CreateUploadStepsResponse, error) {
	out := new(CreateUploadStepsResponse)
	err := c.cc.Invoke(ctx, UploadStateService_CreateUploadSteps_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uploadStateServiceClient) CreateRenditions(ctx context.Context, in *CreateRenditionsRequest, opts ...grpc.CallOption) (*CreateRenditionsResponse, error) {
	out := new(CreateRenditionsResponse)
	err := c.cc.Invoke(ctx, UploadStateService_CreateRenditions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uploadStateServiceClient) ListPendingRenditions(ctx context.Context, in *ListPendingRenditionsRequest, opts ...grpc.CallOption) (*ListPendingRenditionsResponse, error) {
	out := new(ListPendingRenditionsResponse)
	err := c.cc.Invoke(ctx, UploadStateService_ListPendingRenditions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uploadStateServiceClient) UpdateRendition(ctx context.Context, in *UpdateRenditionRequest, opts ...grpc.CallOption) (*UpdateRenditionResponse, error) {
	out := new(UpdateRenditionResponse)
	err := c.cc.Invoke(ctx, UploadStateService_UpdateRendition_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UploadStateServiceServer is the server API for UploadStateService service.
// All implementations must embed UnimplementedUploadStateServiceServer
// for forward compatibility
type UploadStateServiceServer interface {
	GetUploadProcessingContext(context.Context, *GetUploadProcessingContextRequest) (*GetUploadProcessingContextResponse, error)
	UpdateUploadStatus(context.Context, *UpdateUploadStatusRequest) (*UpdateUploadStatusResponse, error)
	UpdateUploadStep(context.Context, *UpdateUploadStepRequest) (*UpdateUploadStepResponse, error)
	UpdateVideoMetadata(context.Context, *UpdateVideoMetadataRequest) (*UpdateVideoMetadataResponse, error)
	CreateUploadSteps(context.Context, *CreateUploadStepsRequest) (*CreateUploadStepsResponse, error)
	CreateRenditions(context.Context, *CreateRenditionsRequest) (*CreateRenditionsResponse, error)
	ListPendingRenditions(context.Context, *ListPendingRenditionsRequest) (*ListPendingRenditionsResponse, error)
	UpdateRendition(context.Context, *UpdateRenditionRequest) (*UpdateRenditionResponse, error)
	mustEmbedUnimplementedUploadStateServiceServer()
}

// UnimplementedUploadStateServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUploadStateServiceServer struct {
}

func (UnimplementedUploadStateServiceServer) GetUploadProcessingContext(context.Context, *GetUploadProcessingContextRequest) (*GetUploadProcessingContextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUploadProcessingContext not implemented")
}
func (UnimplementedUploadStateServiceServer) UpdateUploadStatus(context.Context, *UpdateUploadStatusRequest) (*UpdateUploadStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUploadStatus not implemented")
}
func (UnimplementedUploadStateServiceServer) UpdateUploadStep(context.Context, *UpdateUploadStepRequest) (*UpdateUploadStepResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUploadStep not implemented")
}
func (UnimplementedUploadStateServiceServer) UpdateVideoMetadata(context.Context, *UpdateVideoMetadataRequest) (*UpdateVideoMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVideoMetadata not implemented")
}
func (UnimplementedUploadStateServiceServer) CreateUploadSteps(context.Context, *CreateUploadStepsRequest) (*CreateUploadStepsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUploadSteps not implemented")
}
func (UnimplementedUploadStateServiceServer) CreateRenditions(context.Context, *CreateRenditionsRequest) (*CreateRenditionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRenditions not implemented")
}
func (UnimplementedUploadStateServiceServer) ListPendingRenditions(context.Context, *ListPendingRenditionsRequest) (*ListPendingRenditionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPendingRenditions not implemented")
}
func (UnimplementedUploadStateServiceServer) UpdateRendition(context.Context, *UpdateRenditionRequest) (*UpdateRenditionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRendition not implemented")
}
func (UnimplementedUploadStateServiceServer) mustEmbedUnimplementedUploadStateServiceServer() {}

// UnsafeUploadStateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UploadStateServiceServer will
// result in compilation errors.
type UnsafeUploadStateServiceServer interface {
	mustEmbedUnimplementedUploadStateServiceServer()
}

func RegisterUploadStateServiceServer(s grpc.ServiceRegistrar, srv UploadStateServiceServer) {
	s.RegisterService(&UploadStateService_ServiceDesc, srv)
}

func _UploadStateService_GetUploadProcessingContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUploadProcessingContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploadStateServiceServer).GetUploadProcessingContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UploadStateService_GetUploadProcessingContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploadStateServiceServer).GetUploadProcessingContext(ctx, req.(*GetUploadProcessingContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UploadStateService_UpdateUploadStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUploadStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploadStateServiceServer).UpdateUploadStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UploadStateService_UpdateUploadStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploadStateServiceServer).UpdateUploadStatus(ctx, req.(*UpdateUploadStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UploadStateService_UpdateUploadStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUploadStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploadStateServiceServer).UpdateUploadStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UploadStateService_UpdateUploadStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploadStateServiceServer).UpdateUploadStep(ctx, req.(*UpdateUploadStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UploadStateService_UpdateVideoMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVideoMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploadStateServiceServer).UpdateVideoMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UploadStateService_UpdateVideoMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploadStateServiceServer).UpdateVideoMetadata(ctx, req.(*UpdateVideoMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UploadStateService_CreateUploadSteps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUploadStepsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploadStateServiceServer).CreateUploadSteps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UploadStateService_CreateUploadSteps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploadStateServiceServer).CreateUploadSteps(ctx, req.(*CreateUploadStepsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UploadStateService_CreateRenditions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRenditionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploadStateServiceServer).CreateRenditions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UploadStateService_CreateRenditions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploadStateServiceServer).CreateRenditions(ctx, req.(*CreateRenditionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UploadStateService_ListPendingRenditions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingRenditionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploadStateServiceServer).ListPendingRenditions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UploadStateService_ListPendingRenditions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploadStateServiceServer).ListPendingRenditions(ctx, req.(*ListPendingRenditionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UploadStateService_UpdateRendition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRenditionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploadStateServiceServer).UpdateRendition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UploadStateService_UpdateRendition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploadStateServiceServer).UpdateRendition(ctx, req.(*UpdateRenditionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UploadStateService_ServiceDesc is the grpc.ServiceDesc for UploadStateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UploadStateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "upload.UploadStateService",
	HandlerType: (*UploadStateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUploadProcessingContext",
			Handler:    _UploadStateService_GetUploadProcessingContext_Handler,
		},
		{
			MethodName: "UpdateUploadStatus",
			Handler:    _UploadStateService_UpdateUploadStatus_Handler,
		},
		{
			MethodName: "UpdateUploadStep",
			Handler:    _UploadStateService_UpdateUploadStep_Handler,
		},
		{
			MethodName: "UpdateVideoMetadata",
			Handler:    _UploadStateService_UpdateVideoMetadata_Handler,
		},
		{
			MethodName: "CreateUploadSteps",
			Handler:    _UploadStateService_CreateUploadSteps_Handler,
		},
		{
			MethodName: "CreateRenditions",
			Handler:    _UploadStateService_CreateRenditions_Handler,
		},
		{
			MethodName: "ListPendingRenditions",
			Handler:    _UploadStateService_ListPendingRenditions_Handler,
		},
		{
			MethodName: "UpdateRendition",
			Handler:    _UploadStateService_UpdateRendition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "upload.proto",
}
