// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: upload.proto

package upload

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateUploadStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // e.g. "processing", "finished", "failed"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUploadStatusRequest) Reset() {
	*x = UpdateUploadStatusRequest{}
	mi := &file_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUploadStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUploadStatusRequest) ProtoMessage() {}

func (x *UpdateUploadStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUploadStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateUploadStatusRequest) Descriptor() ([]byte, []int) {
	return file_upload_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateUploadStatusRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UpdateUploadStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateUploadStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUploadStatusResponse) Reset() {
	*x = UpdateUploadStatusResponse{}
	mi := &file_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUploadStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUploadStatusResponse) ProtoMessage() {}

func (x *UpdateUploadStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUploadStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateUploadStatusResponse) Descriptor() ([]byte, []int) {
	return file_upload_proto_rawDescGZIP(), []int{1}
}

type UpdateUploadStepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Step          string                 `protobuf:"bytes,2,opt,name=step,proto3" json:"step,omitempty"`                                     // e.g. "metadata", "transcode", "thumbnail", "moderation"
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                 // e.g. "running", "done", "failed"
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // optional, for failures
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUploadStepRequest) Reset() {
	*x = UpdateUploadStepRequest{}
	mi := &file_upload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUploadStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUploadStepRequest) ProtoMessage() {}

func (x *UpdateUploadStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUploadStepRequest.ProtoReflect.Descriptor instead.
func (*UpdateUploadStepRequest) Descriptor() ([]byte, []int) {
	return file_upload_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUploadStepRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UpdateUploadStepRequest) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *UpdateUploadStepRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateUploadStepRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UpdateUploadStepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUploadStepResponse) Reset() {
	*x = UpdateUploadStepResponse{}
	mi := &file_upload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUploadStepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUploadStepResponse) ProtoMessage() {}

func (x *UpdateUploadStepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_upload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUploadStepResponse.ProtoReflect.Descriptor instead.
func (*UpdateUploadStepResponse) Descriptor() ([]byte, []int) {
	return file_upload_proto_rawDescGZIP(), []int{3}
}

type UpdateVideoMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`                                // container/codec from metadata extraction (empty = no change)
	DurationSec   float64                `protobuf:"fixed64,3,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"` // 0 = no change
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                                // e.g. "ready" when pipeline completes (empty = no change)
	Width         int32                  `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVideoMetadataRequest) Reset() {
	*x = UpdateVideoMetadataRequest{}
	mi := &file_upload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVideoMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVideoMetadataRequest) ProtoMessage() {}

func (x *UpdateVideoMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVideoMetadataRequest.ProtoReflect.Descriptor instead.
func (*UpdateVideoMetadataRequest) Descriptor() ([]byte, []int) {
	return file_upload_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateVideoMetadataRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *UpdateVideoMetadataRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *UpdateVideoMetadataRequest) GetDurationSec() float64 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *UpdateVideoMetadataRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateVideoMetadataRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *UpdateVideoMetadataRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type UpdateVideoMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVideoMetadataResponse) Reset() {
	*x = UpdateVideoMetadataResponse{}
	mi := &file_upload_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVideoMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVideoMetadataResponse) ProtoMessage() {}

func (x *UpdateVideoMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_upload_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVideoMetadataResponse.ProtoReflect.Descriptor instead.
func (*UpdateVideoMetadataResponse) Descriptor() ([]byte, []int) {
	return file_upload_proto_rawDescGZIP(), []int{5}
}

type CreateUploadStepsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Steps         []string               `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"` // e.g. ["metadata", "transcode", "thumbnail", "moderation"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadStepsRequest) Reset() {
	*x = CreateUploadStepsRequest{}
	mi := &file_upload_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadStepsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadStepsRequest) ProtoMessage() {}

func (x *CreateUploadStepsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upload_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadStepsRequest.ProtoReflect.Descriptor instead.
func (*CreateUploadStepsRequest) Descriptor() ([]byte, []int) {
	return file_upload_proto_rawDescGZIP(), []int{6}
}

func (x *CreateUploadStepsRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *CreateUploadStepsRequest) GetSteps() []string {
	if x != nil {
		return x.Steps
	}
	return nil
}

type CreateUploadStepsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadStepsResponse) Reset() {
	*x = CreateUploadStepsResponse{}
	mi := &file_upload_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadStepsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadStepsResponse) ProtoMessage() {}

func (x *CreateUploadStepsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_upload_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadStepsResponse.ProtoReflect.Descriptor instead.
func (*CreateUploadStepsResponse) Descriptor() ([]byte, []int) {
	return file_upload_proto_rawDescGZIP(), []int{7}
}

var File_upload_proto protoreflect.FileDescriptor

const file_upload_proto_rawDesc = "" +
	"\n" +
	"\fupload.proto\x12\x06upload\"P\n" +
	"\x19UpdateUploadStatusRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x1c\n" +
	"\x1aUpdateUploadStatusResponse\"\x87\x01\n" +
	"\x17UpdateUploadStepRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x12\n" +
	"\x04step\x18\x02 \x01(\tR\x04step\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\x1a\n" +
	"\x18UpdateUploadStepResponse\"\x8a\x01\n" +
	"\x1aUpdateVideoMetadataRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12!\n" +
	"\fduration_sec\x18\x03 \x01(\x01R\vdurationSec\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\x1d\n" +
	"\x1bUpdateVideoMetadataResponse\"M\n" +
	"\x18CreateUploadStepsRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x14\n" +
	"\x05steps\x18\x02 \x03(\tR\x05steps\"\x1b\n" +
	"\x19CreateUploadStepsResponse2\x82\x03\n" +
	"\x12UploadStateService\x12[\n" +
	"\x12UpdateUploadStatus\x12!.upload.UpdateUploadStatusRequest\x1a\".upload.UpdateUploadStatusResponse\x12U\n" +
	"\x10UpdateUploadStep\x12\x1f.upload.UpdateUploadStepRequest\x1a .upload.UpdateUploadStepResponse\x12^\n" +
	"\x13UpdateVideoMetadata\x12\".upload.UpdateVideoMetadataRequest\x1a#.upload.UpdateVideoMetadataResponse\x12X\n" +
	"\x11CreateUploadSteps\x12 .upload.CreateUploadStepsRequest\x1a!.upload.CreateUploadStepsResponseB2Z0github.com/LgAcerbi/go-video-upload/proto/uploadb\x06proto3"

var (
	file_upload_proto_rawDescOnce sync.Once
	file_upload_proto_rawDescData []byte
)

func file_upload_proto_rawDescGZIP() []byte {
	file_upload_proto_rawDescOnce.Do(func() {
		file_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_upload_proto_rawDesc), len(file_upload_proto_rawDesc)))
	})
	return file_upload_proto_rawDescData
}

var file_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_upload_proto_goTypes = []any{
	(*UpdateUploadStatusRequest)(nil),   // 0: upload.UpdateUploadStatusRequest
	(*UpdateUploadStatusResponse)(nil),  // 1: upload.UpdateUploadStatusResponse
	(*UpdateUploadStepRequest)(nil),     // 2: upload.UpdateUploadStepRequest
	(*UpdateUploadStepResponse)(nil),    // 3: upload.UpdateUploadStepResponse
	(*UpdateVideoMetadataRequest)(nil),  // 4: upload.UpdateVideoMetadataRequest
	(*UpdateVideoMetadataResponse)(nil), // 5: upload.UpdateVideoMetadataResponse
	(*CreateUploadStepsRequest)(nil),    // 6: upload.CreateUploadStepsRequest
	(*CreateUploadStepsResponse)(nil),   // 7: upload.CreateUploadStepsResponse
}
var file_upload_proto_depIdxs = []int32{
	0, // 0: upload.UploadStateService.UpdateUploadStatus:input_type -> upload.UpdateUploadStatusRequest
	2, // 1: upload.UploadStateService.UpdateUploadStep:input_type -> upload.UpdateUploadStepRequest
	4, // 2: upload.UploadStateService.UpdateVideoMetadata:input_type -> upload.UpdateVideoMetadataRequest
	6, // 3: upload.UploadStateService.CreateUploadSteps:input_type -> upload.CreateUploadStepsRequest
	1, // 4: upload.UploadStateService.UpdateUploadStatus:output_type -> upload.UpdateUploadStatusResponse
	3, // 5: upload.UploadStateService.UpdateUploadStep:output_type -> upload.UpdateUploadStepResponse
	5, // 6: upload.UploadStateService.UpdateVideoMetadata:output_type -> upload.UpdateVideoMetadataResponse
	7, // 7: upload.UploadStateService.CreateUploadSteps:output_type -> upload.CreateUploadStepsResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_upload_proto_init() }
func file_upload_proto_init() {
	if File_upload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_upload_proto_rawDesc), len(file_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_upload_proto_goTypes,
		DependencyIndexes: file_upload_proto_depIdxs,
		MessageInfos:      file_upload_proto_msgTypes,
	}.Build()
	File_upload_proto = out.File
	file_upload_proto_goTypes = nil
	file_upload_proto_depIdxs = nil
}
